apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-proxy-conf
  namespace: default
data: 
  default.conf: |
    # Frontend
    server {
      listen 80;
      server_name  sky.tarunn.co;

      location / {
        proxy_pass <PASS TO FRONTEND>;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

      }
    }

    server {
      listen 80;
      server_name  api.tarunn.co;

      location / {
        proxy_pass <PASS TO BACKEND>;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

      }
    }

    # Custom Nginx server
    server {
      listen 80 ;
      server_name project.tarunn.co;

      location / {
        proxy_pass <PASS TO DYNAMIC NGINX>;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
    }

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
        - name: nginx
          image: nginx:lts-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-proxy-conf

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: nginx-proxy
  ports:
    - name: http
      port: 80
      targetPort: 80