apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-proxy-conf
  namespace: default
data:
  default.conf: |
    server {
      listen 80;
      server_name sky.tarunn.co;

      location /api/ {
        proxy_buffering off;
        proxy_read_timeout 180s;
        proxy_send_timeout 180s;
        proxy_pass http://backend-service.default.svc.cluster.local:3001/;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

      location / {
        proxy_pass http://frontend-service.default.svc.cluster.local:3000;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
    }

    server {
      listen 80;
      server_name api.tarunn.co;

      location / {
        proxy_pass http://backend-service.default.svc.cluster.local:3001;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
    }

    server {
      listen 80;
      server_name project.tarunn.co;

      location / {
        proxy_pass http://nginx-custom.default.svc.cluster.local:8080;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-proxy-conf
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: nginx-proxy
  ports:
    - name: http
      port: 80
      targetPort: 80
