export enum Tools {
  CREATE_SUB_AGENT,
  WAITING_FOR_SUB_AGENT,
  GET_CURRENT_WORKSPACE,
  EXECUTE_BASH,
  READ_DIR,
  READ_FILE,
  CREATE_FILE,
  DELETE_FILE,
  UPDATE_FILE,
  TAKE_INPUT,
  CREATE_PLAN,
  INFORM_TASK_COMPLETION,
}
