# For auth
# https://github.com/google-github-actions/auth/blob/main/README.md#direct-wif

# authenticate to google cloud gcp from github actions using oidc and workload identity
# https://medium.com/@prasad.reddy0708/authenticate-to-google-cloud-gcp-from-github-actions-using-oidc-and-workload-identity-federation-2a6c6b56c29f

name: Deploy 
run-name: Deploy Kubernetes manifests

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:

      - uses: 'actions/checkout@v4'

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      # Authenticate to GCP using Workload Identity Federation
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v3
        with:
          token_format: "access_token"
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          
      # get kubernetes creds so that kubectl work
      - name: Get GKE Credentials
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: 'hundred-x-course'
          location: 'asia-southeast1'


      # Create the secrets in k8s for other deployments to use
      - name: Create secret in main cluster
        run: |
          kubectl create secret generic sky-secrets --namespace=default \
            --from-literal=DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            --from-literal=GCP_PROJECT_ID="${{ secrets.GCP_PROJECT_ID }}" \
            --from-literal=POSTGRES_USER="${{ secrets.POSTGRES_USER }}" \
            --from-literal=POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}" \
            --from-literal=POSTGRES_DB="${{ secrets.POSTGRES_DB }}" \
            --dry-run=client -o yaml | kubectl apply -f -

        # deploy the docker images to k8s
      - name: Deploy apps
        run: |
          kubectl apply -f ./infra/pvc.yml
          kubectl apply -f ./infra/postgres.yml
          kubectl apply -f ./infra/ingress.yml
          kubectl apply -f ./infra/dynamic_ngi nx/deployment.yml
        # kubectl apply -f ./infra/apps/backend
        # kubectl apply -f ./infra/apps/frontend

      - name: Wait for Postgres
        run: |
          kubectl rollout status deployment/sky-postgres